### PR TITLE
Fix lxml compilation errors in Ubuntu 14.04 LTS

### PR DESCRIPTION
**Pull request by olifante**
Hello @jean, your fork fixes a lot of problems with the upstream repo, but I still couldn't get it to run successfully. Lxml failed to compile during the task [sentry | install sentry and create virtualenv if needed].

These stackoverflow comments helped me get lxml to compile with Ubuntu 14.04 LTS, both in vagrant and on digital ocean (I had to increase the droplet memory capacity to 1024 MB):
- 1024 MB of RAM is needed: http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu/25372234#25372234
- zlib1g-dev is needed: http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu/19289133#19289133
- pyopenssl, ndg-httpsclient and pyasn1 are needed: http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent/29202163#29202163

### CODE REVIEW

**Comment by jean** [comment]
Hi @olifante -- at least some of these (such as the droplet size) are addressed in my `digitalocean` branch (https://github.com/jean/sentry-ansible-vagrant/tree/digitalocean). 
I didn't run into the `zlib1g-dev` issue (but I see I have `libz-dev` from Dar Bentov merged), but I needed to add `libjpeg-dev` and `redis-server`. 
Do you think the DO changes should go into `master`? Maybe as e.g. a `Vagrantfile-digitalocean`?

**Comment by olifante** [comment]
I think the DO changes should go into master. After all, there's nothing DO-specific there, it's just a server IP. The whole point of the vagrant setup is surely to help debug your ansible script for eventually deploying to some external server, hosted on DO or somewhere else.

I'm a bit confused by your comment about the DO-specific Vagrantfile. Do you mean you have an image of a DO droplet that you run locally on a Vagrant virtual machine? If so, that's not what I do. Once I'm satisfied that the ansible script works correctly on a basic Ubuntu image, I deploy to DO using something like provision.sh.

**Comment by jean** [comment]
@olifante 

> I think the DO changes should go into master.

OK, I agree, I'll merge. 

> I'm a bit confused by your comment about the DO-specific Vagrantfile.

Well, the DO one would have config like `...vm.box = "digital_ocean"`, `provider.token = "...."`, `provider.size = "1gb"` etc.

I think the way to deal with this would be to use the `--provider` and `--provision-with` arguments to `vagrant`.

I'll try and merge my `digitalocean` branch today, and incorporate anything I'm still missing from your PR. Thanks for helping me think!

**Comment by olifante** [comment]
@jean updated pull request by merging your changes
